model:
  class_path: pretrain.model.Lyrics2MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 16
      position: 256
      duration: 256
      pitch: 256
      tempo: 128
      velocity: 128
      lyrics: 768
      group: 256
      phrase: 256
      token_type: 16
      task_id: 16
    cutoffs: [400, 1000]
    use_adaptive_embedding: true
    model_dim: 1024
    feedforward_dim: 2048
    num_layers: 4
    num_heads: 8
    dropout: 0.1
    lr: 3.5e-4
    betas: [0.9, 0.98]
    epsilon: 1e-6
    weight_decay: 0.01
    warmup_percent: 0.2