# lightning.pytorch==2.1.0
seed_everything: 42
trainer:
  accelerator: gpu
  devices: [0]
  precision: 16-mixed
  max_steps: 200000
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step